"""document ocr_used

Revision ID: 0003
Revises: 0002
Create Date: 2026-10-01 16:46:41.300428

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0003"
down_revision: str | Sequence[str] | None = "0002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "documents", sa.Column("ocr_used", sa.Boolean(), server_default="false", nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("documents", "ocr_used")
    # ### end Alembic commands ###
